version: 2
updates:
  - package-ecosystem: "npm" # You’re using npm as the package manager
    directory: "/" # Path where package.json is located
    schedule:
      interval: "weekly" # Weekly checks for updates
